package com.thomas.core.exception

enum class ErrorType {

    UNRESOLVED_ORGANIZATION,
    UNAUTHENTICATED_USER,
    UNAUTHORIZED_ACTION,
    INVALID_ENTITY,
    INVALID_PARAMETER,
    NOT_FOUND,
    APPLICATION_ERROR,

}
